### PR TITLE
Add entries to CHANGELOG for 4.1

### PR DESCRIPTION
**Pull request by jaym**

### CODE REVIEW

**Comment by yzl** [comment]
lgtm

**Comment by schisamo** [comment]
This looks great @jaym. We need to begin instructing people to update the CHANGELOG as part of their PR. What do you think about that @chef/omnibus-maintainers?

**Comment by danielsdeleo** [comment]
The crappy part is that git doesn't know how to merge changelog entries well, so everything conflicts. Not really a good solution that I know of.

**Comment by jaym** [comment]
i generally update the changelog in a different PR. That being said, we just need to get into the habit of doing it

**Comment by sethvargo** [comment]
@schisamo one thing we do on Vagrant that's proved to be useful is this:

1. Tell people *do not update the changelog or bump the version* in PRs
2. Merge PRs
3. After merging, pull changes locally, commit a changelog entry for that merged PR and link back to the PR

It's a bit tedious, but it sure beats going through commits after and reduces the chances of a merge conflict.

**Pull request merged**
