### PR TITLE
Fix copy paste error from bff log loop

### PR DESCRIPTION
**Pull request by scotthain**

### CODE REVIEW

**Comment by schisamo** [comment]
:+1: 

/cc @chef/engineering-services

**Comment by curiositycasualty** [comment]
-_-' :+1:

**Comment by yzl** [comment]
:+1:

**Comment by schisamo** [comment]
Successful test @scotthain ran: http://manhattan.ci.chef.co/job/harmony-trigger-ad_hoc/29/downstreambuildview/

**Pull request merged**
