### PR TITLE
Raspberry Pi 2 support

### PR DESCRIPTION
**Pull request by xenolinguist**
Provide correct arch string for Ubuntu on Raspberry Pi 2

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @xenolinguist

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by xenolinguist** [comment]
Not sure why Curry doesn't think I'm an employee.

**Comment by xenolinguist** [comment]
This also overlaps with #474, but that PR only supports Raspbian on Pi2 and not Ubuntu.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by schisamo** [comment]
:+1: 

/cc @chef/omnibus-maintainers

**Comment by sethvargo** [comment]
LGTM

**Comment by danielsdeleo** [comment]
:+1:

**Pull request merged**
