### PR TITLE
Prepare v5.0.0 release

### PR DESCRIPTION
**Pull request by schisamo**
CHANGELOG based on:
https://github.com/chef/omnibus/compare/v4.1.0...HEAD

/cc @chef/omnibus-maintainers

### CODE REVIEW

**Comment by scotthain** [comment]
:+1: :confetti_ball:

**Comment by jaym** [comment]
YAY

**Comment by curiositycasualty** [comment]
:rocket: :cake:

**Comment by stevendanna** [comment]
:+1: :shipit:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by yzl** [comment]
:ice_cream:

**Comment by schisamo** [comment]
Cherry-picked as c078b22.

**Pull request closed without merging**
