### PR TITLE
Remove version constrain on chefstyle

### PR DESCRIPTION
**Pull request by tas50**
We should let chefstyle float

### CODE REVIEW

**Comment by lamont-granquist** [comment]
as long as you understand that i'm not signing up to submit PRs against all the downstream repos every time i do a release of chefstyle...   so i'll do my roughly quarterly chefstyle release and then travis will go red here...

**Comment by tas50** [comment]
If we think it's our style guide we should be prepared to fix it as we do releases of the various projects. Otherwise we have multiple different versions of the style guide implemented across projects as we slowly upgrade everything to the latest release.

**Comment by lamont-granquist** [comment]
as long as the pain of upgrades are decentralized...

**Pull request merged**
