### PR TITLE
Change the appbundler DSL to not make an apps dir

### PR DESCRIPTION
**Pull request by ksubrama**
Also enable functional tests on windows.

### CODE REVIEW

**Comment by sethvargo** [comment]
Code looks good, but what is the motivation?

**Comment by jaym** [comment]
I feel like this will break windows upgrades for chef

**Comment by danielsdeleo** [comment]
Don't the tests rely on having the full source code in the apps/ directory?

**Comment by ksubrama** [comment]
@jaym It absolutely will - but not for the service. It's break for the ETW dll we register.  I am making changes to the chef repo itself to include that dll in the chef gem on windows so that our event registration code can point to that instead.  The service is ok because it points to a path in opscode/chef/bin which will correctly point to the gem (that was your fix for 12.4.3 right?).

**Comment by ksubrama** [comment]
@sethvargo This was our attempt to not include multiple copies of our apps because there was an incident where a chef plugin somehow ended up including a file from the chef gem instead of the copy of chef from the apps directory which caused a conflicting redefinition of a module.

**Comment by ksubrama** [comment]
@danielsdeleo The full source tree is already in the gem directory.  We'd just have to change the test scripts to look in there instead.

**Comment by danielsdeleo** [comment]
That's fine, but we should have that change queued up so we're not busted in the interim.

**Comment by ksubrama** [comment]
Changed to omnibus software https://github.com/chef/omnibus-software/pull/500

**Comment by ksubrama** [comment]
Changed to omnibus-chef https://github.com/chef/omnibus-software/pull/500

**Comment by danielsdeleo** [comment]
FYI, the "verify" code in chef-dk seems to assume the presence of the apps/ dir quite heavily: https://github.com/chef/chef-dk/blob/master/lib/chef-dk/command/verify.rb

**Comment by ksubrama** [comment]
Changes to chef-dk https://github.com/chef/chef-dk/pull/562

**Pull request merged**
