### PR TITLE
Make generated package scripts old-school Unix friendly

### PR DESCRIPTION
**Pull request by schisamo**
This matches the scripts we use in the Chef project. This change has been tested across the full Chef matrix in the context of the Harmony integration project also:
https://github.com/chef/omnibus-harmony/pull/13
http://manhattan.ci.chef.co/job/harmony-trigger-ad_hoc/5/downstreambuildview/

/cc @chef/omnibus-maintainers @chef/engineering-services

### CODE REVIEW

**Comment by scotthain** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1: 

you should really `apt-get install checkbashisms` and then run it across these scripts just like rubocop...

**Comment by curiositycasualty** [comment]
@lamont-granquist:
```
 system  isa  Development/chef/omnibus-harmony  checkbashisms -x package-scripts/harmony/*                                                                      master ✔  ✔ 0
 system  isa  Development/chef/omnibus-harmony  echo $?                                                                                                         master ✔  ✔ 0
0
```

**Comment by lamont-granquist** [comment]
sorry by 'just like rubocop' i meant 'put in .travis.yml'

**Comment by schisamo** [comment]
@lamont-granquist The issue is they are ERB templates that generate shell scripts. I suppose the functional test suite could generate a project and perform that type of check.

**Comment by lamont-granquist** [comment]
i actually ran it on install.sh.erb and it worked fine...  i was expecting it to puke but it skipped over the erb in that....

**Pull request merged**
