### PR TITLE
Gemfile declaration for pedump is overwritten by onmnibus.gemspec fix for #629.

### PR DESCRIPTION
**Pull request by rsb**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @rsb

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by jaym** [comment]
probably want to do a conditional require of pedump if we do this?

**Comment by rsb** [comment]
This dependency was introduced a few commits ago which looks like its isolated to Omnibus::HealthCheck#relocation_check which is only exposed via the HealthCheck.run! used in OmniBus::Project#build. It appears to be needed only for a windows platform so I guess you could move the require the method that uses it, but I would not want to do that because you look the declaration at the top of the file which allows the developer orient themselves to the dependencies involved. I am not sure what you want to do?

**Comment by ksubrama** [comment]
Something like this at the top of the file.

```
begin
  require 'pedump'
rescue LoadError
  STDERR.puts "pedump not found - windows health checks disabled"
end
```

You can then do a similar thing inside `run!` by requiring pedump again just before calling `relocation_check` and only calling that method if it didn't throw a LoadError.

**Comment by rsb** [comment]
can I define a constant and check for that, to avoid the second require
```ruby
begin
  require 'pedump'
rescue LoadError
   LOAD_FAILURE_PEDUMP_GEM=1
   STDERR.puts "pedump not found - windows health checks disabled"
end
 ```

**Comment by ksubrama** [comment]
You can use a constant if you'd like.

Your test change is incorrect.  Relocation checking *only* works on windows.  That's what
```ruby
conflict_map = relocation_check if windows?
``` was doing.

**Comment by rsb** [comment]
already fixed it, when I released the tests broke.

**Comment by ksubrama** [comment]
Yay simultaneous commenting :)
:+1:

**Comment by ksubrama** [comment]
@chef/omnibus-maintainers

**Comment by rsb** [comment]
I don't believe I have the correct permissions to view that list

**Comment by ksubrama** [comment]
Yeah - don't know why github doesn't let you @ lists that you aren't in.  I was just summoning a few other maintainers to give you +1s.

**Comment by yzl** [comment]
:+1:

**Pull request merged**
