### PR TITLE
Added localization option for msi packager

### PR DESCRIPTION
**Pull request by MrWong99**
### Description

WIX allows users to configure the target localization.
This feature allows a user to override the default localization `en-us` for the msi packager.
The project generator for msi was not changed, but one could generate the localization files for each supported language based on the [standard implementations of wix](https://github.com/wixtoolset/wix3/tree/develop/src/ext/UIExtension/wixlib).

#### Maintainers

Please ensure that you check for:

- [ ] If this change impacts git cache validity, it bumps the git cache
  serial number
- [ ] If this change impacts compatibility with omnibus-software, the
  corresponding change is reviewed and there is a release plan
- [ ] If this change impacts compatibility with the omnibus cookbook, the
  corresponding change is reviewed and there is a release plan

### CODE REVIEW

**Comment by MrWong99** [comment]
Any comment on this? How can I help to get this merged?
Or should I build my own Omnibus gem?

**Comment by marcparadise** [comment]
Thanks for submitting this @MrWong99, and sorry for the delay in getting eyes on this.  
 
Would you be able to recreate this branch based on current master? We should be able to get it merged shortly after.

**Comment by MrWong99** [comment]
Hi @marcparadise and thanks for your response!

I merged the master branch in my feature branch and the CI checks seem to be satisfied.

**Comment by marcparadise** [comment]
Excellent, thanks!

**Comment by MrWong99** [comment]
Thanks for the review!

**Pull request merged**
