### PR TITLE
Even more betterer support for msys2

### PR DESCRIPTION
**Pull request by ksubrama**
### Description

Ensure platform host/build triples get set correctly on windows.
Remove some old code involving bfd flags now that we aren't doing cross-compiling gymnastics.

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

### CODE REVIEW

**Comment by ksubrama** [comment]
@mwrock @schisamo @tyler-ball 

Do not merge this until omnibus-software has removed all mentions of the old msys.

**Comment by mwrock** [comment]
:+1: 
appveyor failure looks transient. I just kicked off a rebuild

**Comment by tyler-ball** [comment]
👍 Thats awesome that you were able to simplify the code!

**Comment by schisamo** [comment]
👍

**Pull request merged**
