### PR TITLE
Get Omnibus building on Windows 10

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by jaym** [comment]
awesome
On a related note, will https://github.com/chef/chef/blob/master/lib/chef/win32/version.rb#L51 need updating as well?

**Comment by schisamo** [comment]
Let's add a test please.

**Comment by danielsdeleo** [comment]
:+1: modulo adding tests and doing a build to confirm this is all that's needed.

**Comment by scotthain** [comment]
:+1: + what they said about tests :)

**Comment by jkeiser** [comment]
@danielsdeleo I've done a ChefDK build on Win10, and it installs and runs for sure. I'll get a test in there, thanks--wanted to confirm I was going the right path first!

**Comment by thommay** [comment]
Yup, used this branch yesterday to build delivery-cli on Win 10, works delightfully :+1:

**Pull request merged**
