### PR TITLE
Add Appveyor for Windows testing

### PR DESCRIPTION
**Pull request by schisamo**
/cc @chef/omnibus-maintainers

### CODE REVIEW

**Comment by sethvargo** [comment]
I don't know anything about appveyor, so I'll defer here :smile:

**Comment by schisamo** [comment]
It looks like we are going to have to do some fixes in our tests before the Appveyor testing. I'm just going to leave this PR open for now though.

**Comment by ksubrama** [comment]
:+1:

**Comment by schisamo** [comment]
This was replaced by https://github.com/chef/omnibus/pull/522.

**Pull request closed without merging**
