### PR TITLE
Added documentation about whitelisting libraries

### PR DESCRIPTION
**Pull request by scotthain**
@chef/omnibus-maintainers

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Can you add some guidelines to help people understand the health check and when they should or should not whitelist? E.g., "you should only add libraries to the whitelist that are guaranteed to be on the system you install to, if a library comes from a non-default package you should instead build it into the package"

**Comment by scotthain** [comment]
@danielsdeleo great idea, I borrowed exactly what you said there because I couldn't think of a better way to explain it :)

**Comment by yzl** [comment]
lgtm

**Comment by danielsdeleo** [comment]
:+1:

**Comment by schisamo** [comment]
:+1:

**Pull request merged**
