### PR TITLE
Whitelist additional Solaris11 libraries

### PR DESCRIPTION
**Pull request by jaymalasinha**
### Description

Whitelist additional Solaris11 libraries

--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

### CODE REVIEW

**Comment by scotthain** [comment]
@lamont-granquist le sigh

**Comment by lamont-granquist** [comment]
Solaris...

:+1: i guess?

although travis is all angrysauce for some reason...

**Comment by schisamo** [comment]
Looks like the specs need some updating.

**Comment by jaymalasinha** [comment]
@chef/engineering-services - tested changes passed in CI on build: http://manhattan.ci.chef.co/job/angrychef-trigger-ad_hoc/28/

**Pull request merged**
