### PR TITLE
Fix git/path fetcher to request the correct version from cache.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by scotthain** [comment]
Is there a way to try and replicate the original issue and ensure this fixes it?

**Comment by ksubrama** [comment]
@scotthain We could always try to build chef while pointing it to some dummy branch, then push a change up to that branch and retry to build to verify it pulls down the new commits.

**Comment by scotthain** [comment]
@ksubrama that would make me personally happy :)

**Comment by ksubrama** [comment]
Confirmed.  I left my Gemfile.lock in chef/chef:omnibus pointer to master of omnibus.  I pushed a branch dummy1 with 1 commit.  I then branched off of that, made another commit and pushed up dummy2.

Now back from master, I edited the chef omnibus project to build dummy1.  It built it fine.  I asked to build it again and it restored fro cache.  Now I FF-merge dummy1 up to dummy2 and push that.  Build again (making sure not to edit the project file or anything else that might invalidate the cache).  This time it still restored from cache (that's our bug). I now updated Gemfile.lock to point to this branch.  Built again - all but chef got restored from cache.  Chef was fetched afresh.

**Comment by ksubrama** [comment]
I should turn that into an actual functional test at some point.  It's on my long list of TODOs.

**Comment by schisamo** [comment]
:+1:

**Comment by yzl** [comment]
:+1:

**Pull request merged**
