### PR TITLE
Update submodules on git checkout

### PR DESCRIPTION
**Pull request by szechyjs**

### CODE REVIEW

**Comment by ksubrama** [comment]
:+1:

**Comment by scotthain** [comment]
I feel like this caused an issue at some point in the past? @chef/engineering-services

**Comment by szechyjs** [comment]
Have we made any decisions on this yet?

I currently have to use the following hack in my software definitions.

```ruby
command 'git submodule update', env: env
```

**Comment by ksubrama** [comment]
@schisamo @scotthain I am personally +1 on this and think it's essential.  git cache has received numerous bug-fixes recently and I don't believe this should cause us any breakage unless we have platforms that outright break on submodules (which is a different problem - they'll fail anyway).

**Comment by rhass** [comment]
The `enable_submodules` property in Chef uses the same behavior. 
https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L174
I am in favor of doing this to keep thing consistent. :+1: 

If problems do arise we can always make something like `update_submodules` as a separate parameter.

**Comment by yzl** [comment]
:+1:

**Pull request merged**
