### PR TITLE
Clone git repositories with --recursive flag.

### PR DESCRIPTION
**Pull request by szechyjs**
If the repo contains any submodules this will initialize them after the clone completes.

### CODE REVIEW

**Comment by sethvargo** [comment]
I'm :+1: on this, but I wonder if there is a situation where a user would _not_ want submodules. Maybe it makes sense to have a `:submodules` option that defaults to false that can be specified in the software config? Like `source git: "...", submodules: true`. Thoughts?

**Comment by szechyjs** [comment]
I like the idea of the :submodules option. I've pushed a change that includes the option.

**Comment by yzl** [comment]
:+1:

**Comment by schisamo** [comment]
:+1:

**Pull request merged**
