### PR TITLE
Be more paranoid when syncing files.

### PR DESCRIPTION
**Pull request by ksubrama**
If a file or a hardlink already exists at the destination,
we need to be careful and remote the existing file before
we perform the copy. A file at the destination can be
marked with r--r--r-- which will throw EACCESS if we blindly
copy from source to destination.

### CODE REVIEW

**Comment by ksubrama** [comment]
There are still a few other use-cases (like source being a hard-link while destination is a read only directory or a symlink to a read only directory) that I'm unsure about that the code present fixes an issue we've encountered and I don't really feel like digging through the man pages of all our platforms for synthetic scenarios that we haven't encountered.

**Comment by scotthain** [comment]
@curiositycasualty you ran into some of this oddness didn't you?

**Comment by curiositycasualty** [comment]
Yeah but it looks like this should take care of it. Ideally, this would be a use-case added to harmony. @scotthain

**Comment by schisamo** [comment]
:+1:

**Comment by scotthain** [comment]
Sweet. :+1:

**Pull request merged**
