### PR TITLE
this autoprunes files with spaces

### PR DESCRIPTION
**Pull request by lamont-granquist**
these are most often spec fixtures in rubygems that have spaces in
the filenames.  we keep needing to add delete lines to remove
tests from gems before packaging.  this patch automates that.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/omnibus-maintainers assuming rubocop is happy...

**Comment by schisamo** [comment]
:+1:

**Comment by lamont-granquist** [comment]
so to capture discussion on slack...

this could omit a critical file that we need for runtime which has a space in it.

in that circumstance, though, we're hosed because we can't package files with spaces on solaris.

we should also catch that via some kind of test failure.

the alternative is to periodically break builds when we deploy gems with spec fixtures that have spaces in filenames, and then we have to remember why that happens and go fiddle around manually deleting the file.

so its creating busy work and failed builds, so that we know up front that we broke the build, when we should have tests that will capture that, and we're just completely f***ed anyway if the thing we're worried about ever really happens...

so i don't see the point in not doing this...

**Comment by scotthain** [comment]
I'm cool with it - we should trust our tests :)

**Pull request merged**
