### PR TITLE
Ruby 2.7.1 adds a warning on calling open directly, needs to be URI.open

### PR DESCRIPTION
**Pull request by mattray**
Fixes https://github.com/chef/omnibus/issues/923
https://github.com/ruby/ruby/commit/3816cd945d68eac7ca8fecbc9d71f878ff3e7b3d#diff-0f19cb99597e5fb90bfb937b22143b51

### CODE REVIEW

**Comment by tas50** [comment]
This seems to cause a bunch of spec failures now

**Comment by mattray** [comment]
Looking through the commits in https://github.com/ruby/ruby/commits/master/lib/open-uri.rb it looks like `URI.open` won't work before 2.7 and `open` won't work in 2.7 and later. I'm not much of a Rubyist, so I don't know how to check the Ruby version to provide conditional logic around this.

**Comment by tas50** [comment]
@mattray this kind of thing:

```ruby
      if RUBY_VERSION.to_f < 2.7
        URI.encode(url)
      else
        CGI.escapeHTML(url)
      end
```

**Comment by tas50** [comment]
Thanks @mattray

**Pull request merged**
