### PR TITLE
Add support for arm64 platform in Debian

### PR DESCRIPTION
**Pull request by edolnx**
Greetings @chef/omnibus-maintainers This just makes building packages on 64bit ARM platforms work correctly in Debian. Similar to Raspberry Pi issues.

### CODE REVIEW

**Comment by scotthain** [comment]
:+1:

**Comment by schisamo** [comment]
:+1:

**Comment by yzl** [comment]
:+1:

**Comment by schisamo** [comment]
@edolnx Can we please add some test coverage before merging this?

**Pull request closed without merging**
