### PR TITLE
Optimize the crap out of windows

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
yeah enabling SSE2 is a 2001-era optimization.   :+1:

**Comment by thommay** [comment]
Do we actually want to O3 rather than O2? Just thinking for supportability/stability's sake a slightly less agressive approach might be better

**Comment by lamont-granquist** [comment]
ruby's default has been -O3 since 2009:

https://github.com/ruby/ruby/commit/62e7e47bdb6d5b4f13138bd3290ca3c40d3ddbab

**Comment by thommay** [comment]
Huh. go ahead then! :+1:

**Comment by lamont-granquist** [comment]
These would probably be good as generic options for everything other than AIX/Solaris?  If we're compiling for i586 without any SSE support that's a little bit awful...

**Comment by schisamo** [comment]
@ksubrama remember to /cc @chef/omnibus-maintainers plz.

**Comment by ksubrama** [comment]
Oh woah this got popular.  Sorry @schisamo - I should have marked this WIP.  I just wanted some builds going.

The optimization flags help in most places but some (like openssl) seem to dislike it and I'm currently debugging it.  I'll send this out once I'm confident that it won't break anything.

**Comment by ksubrama** [comment]
Ok, I am ready to merge this.  OpenSSL was actually fine.  This is windows only for now - I'll make a different PR to see what happens if we enable SSE2 on other platforms next.

**Comment by lamont-granquist** [comment]
While you're at it no-exec-stack flags on linux and all that jazz would be good, too, since I'm sure you have no other work to do...

**Pull request merged**
