### PR TITLE
Workaround for deb packagers when OS is Raspbian and arch is armv7l.

### PR DESCRIPTION
**Pull request by maxlazio**
Basically the same thing as in #352 but this time for Raspbian when arch is armv7l.

### CODE REVIEW

**Comment by schisamo** [comment]
:+1:

**Comment by sethvargo** [comment]
:+1:

**Comment by yzl** [comment]
:+1:

**Comment by schisamo** [comment]
This should have been fixed as part of https://github.com/chef/omnibus/pull/498.

**Pull request closed without merging**
