### PR TITLE
Set fetch_dir permanently when entering back-compat mode

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
http://manhattan.ci.chef.co/job/chef-13-build/5/

@chef/omnibus-maintainers

**Comment by schisamo** [comment]
So this case has gotten a little complicated. Can we add unit test coverage?

**Comment by scotthain** [comment]
:+1: modulo passing travis

**Comment by schisamo** [comment]
:+1:

**Comment by ksubrama** [comment]
And travis passes!

**Pull request merged**
