### PR TITLE
use the wixutil extension

### PR DESCRIPTION
**Pull request by mwrock**
This extensin includes the following custom actions:
```
WixBroadcastSettingChange
WixBroadcastEnvironmentChange
```
Including these actions (separate PR to omnibus-chef) properly broadcast environment variable changes and fixes https://github.com/chef/chef-dk/issues/534

### CODE REVIEW

**Comment by schisamo** [comment]
@mwrock Be sure to always /cc @chef/omnibus-maintainers

**Comment by schisamo** [comment]
I would only make this change if we want *all* MSIs produced by Omnibus to do this. If it's just something we want in a single project (like ChefDK or Chef) we should be able to fix this in a project definition using the `wix_light_extension` DSL method for the MSI packager with something like this:

```ruby
package :msi do
  upgrade_code "AB1D6FBD-F9DC-4395-BDAD-26C4541168E7"
  signing_identity "F74E1A68005E8A9C465C3D2FF7B41F3988F0EA09", machine_store: true
  wix_light_extension "WixUtilExtension"
end
```

**Comment by mwrock** [comment]
That's reasonable. This was made solely for dk and I'll figure out where that above snippet needs to live.

**Comment by mwrock** [comment]
I see where thats done. adding to omnibus-chef PR and running another test to validate.

**Pull request closed without merging**
