### PR TITLE
Fix typo when generating log message.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by schisamo** [comment]
Why didn't the tests catch this? We should add coverage now so it doesn't happen again.

**Comment by ksubrama** [comment]
I'm not sure what the best way to add coverage is.  We set Omnibus.logger.level = :nothing in spec_helper and the type I made was inside an interpolated string sent to the logger.  So it didn't blow up because the log statement was never evaluated.

**Comment by schisamo** [comment]
@ksubrama Line 177 isn't inside a log statement right?

**Comment by ksubrama** [comment]
177 wasn't syntactically incorrect.  We never set that parameter to anything but resolved_version - so none of the functional tests failed for that.

**Comment by schisamo** [comment]
@ksubrama Looks good. Let's just remove 839efbc33e0ab3aa31ea29106907598337c42012 and squash this down.

**Pull request merged**
